### ISSUE TITLE
Enum Formatting

### ISSUE THREAD

**Issue by marvinrabe** [marvinrabe/laravel-graphql-test#1]
**Currently:**

    $this->setArguments(['enum' => 'foo'])

results in

    (enum: "foo")

**Expected:**

    $this->setArguments(['enum' => 'foo'])

results in

    (enum: foo)

**Workaround:**

Create a class

```php
class Enum {
  protected $value;

  public function __construct($value) {
    $this->value = $value;
  }

  public function __toString() {
    return $this->value;
  }
}
```

And then:

    $this->setArguments(['enum' => new Enum('foo')])

results in

    (enum: foo)

**Comment by websitevirtuoso** [comment]
Could you tell me or help with this issue. I have the same problem when I need enum and other types like
date or datetime etc.

**Comment by websitevirtuoso** [comment]
I would look at https://github.com/kunicmarko20/graphql-test

I offer to create the same helper classes
use KunicMarko\GraphQLTest\Bridge\Symfony\TestCase;
use KunicMarko\GraphQLTest\Operation\Mutation;
use KunicMarko\GraphQLTest\Type\EnumType;
use KunicMarko\GraphQLTest\Type\BooleanType;
use KunicMarko\GraphQLTest\Type\ArrayType;

**Comment by marvinrabe** [comment]
Sure! Feel free to provide a PR.

**Comment by marvinrabe** [comment]
@websitevirtuoso Thank you for your inspiration. `EnumTypes` are now available.

You might use the provided enum helper:

```php
$this->query('accounts', ['status' => $this->enum('closed')], ['id']);
```
