### ISSUE TITLE
Upgrading to laravel 8

### ISSUE THREAD

**Issue by websitevirtuoso** [marvinrabe/laravel-graphql-test#6]
Hello,
Thak thank you support this project.

I just upgraded one of my projects and got an error in phpDoc.
Your package describes \Illuminate\Foundation\Testing\TestResponse as a returning type.
But In laravel 8 it has been moved to \Illuminate\Testing\TestResponse.

Example: file marvinrabe/laravel-graphql-test/src/TestGraphQL.php

/**
     * Returns a TestGraphQL client. If no arguments and selection is provided, it will query the server directly.
     * @param  string  $object  GraphQL query name
     * @param  array|null  $arguments  Specifies arguments send to the server. When selection is null it will be used as a selection set instead.
     * @param  array|null  $selection  Specifies Selection set send to the server.
     * @return GraphQLClient|\Illuminate\Foundation\Testing\TestResponse
     **/
    public function query(string $object, $arguments = null, $selection = null)
    {
        $client = GraphQLClient::query($object, function ($query) {
            return $this->postJson(
                $this->graphQLEndpoint ?? 'graphql',
                [
                    'query' => $query,
                ]
            );
        });

        return $this->prepareClient($client, $arguments, $selection);
    }

My tests still working but ide inform that It can't find a response and autocomplete doesn't work anymore.
I can create PR just let me know

**Comment by marvinrabe** [comment]
Fixed with Version 0.4.0.
