### ISSUE TITLE
how could we use header in requests

### ISSUE THREAD

**Issue by geeksesi** [marvinrabe/laravel-graphql-test#8]
i want to set authentication header for my test.
how can i do this ?
in `postJson` i can set header parameter. should i edit package manually ? or we have any option to add header in requests.

and also thank you for this package

**Comment by geeksesi** [comment]
i have found some ways.
let me explain for other peoples.
## in each request make some header
before making request ex: 
```
$this->query("report", [], ["contactsResultStatistics"]);
```
you can define header like this with `MakesHttpRequests` trait like this :

```
       $this->withHeaders(["Authorization" => "Bearer TOKEN"]);
       $this->query("report", [], ["contactsResultStatistics"]);
```

## global header in test class 
if you want to set a header for whole class : 
```
class UserMethodOfIntroduction extends TestCase
{
    protected $defaultHeaders = [
        "Authorization" => "Bearer TOKEN",
    ];
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->query("report", [], ["contactsResultStatistics"]);
    }
}
```

**Comment by marvinrabe** [comment]
Thank you! For whatever reason I haven't received a notification. I added this information to the README for others.
